[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs", "csx", "cake"]
roots = ["sln", "csproj"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "\t" }
language-servers = [ { name = "csharp-ls", except-features = [ "format" ] }, "gpt" ]
formatter = { command = "dotnet-csharpier" }
auto-format = true
